name: Run Python Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.11
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: testdb
          MARIADB_USER: testuser
          MARIADB_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mariadb-admin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install MariaDB Connector/C
        run: |
          sudo apt-get update
          sudo apt-get install -y libmariadb-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create dummy config.py
        run: |
          echo "DB_USER='testuser'" > config.py
          echo "DB_PASSWORD='testpass'" >> config.py
          echo "DB_HOST='127.0.0.1'" >> config.py
          echo "DB_NAME='testdb'" >> config.py

      - name: Wait for MariaDB to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h127.0.0.1 -utestuser -ptestpass --silent; then
              echo "MariaDB is up!"
              break
            fi
            echo "Waiting for MariaDB..."
            sleep 2
          done

      - name: Run tests with coverage
        run: |
          pytest --cov=repositories --cov=services --cov=routers --cov-report=html

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov/

