name: Run Python Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install MariaDB Connector/C
        run: |
          sudo apt-get update
          sudo apt-get install -y libmariadb-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=repositories --cov=services --cov=routers --cov-report=html

